### PR TITLE
fix: iOS scanning

### PR DESCRIPTION
**Pull request by patrickpei**
- allows for scanning on iOS devices (tested on iOS 11.3.1 & 11.4)
- temporary demo: [here](https://barcodescanner-jwwuerkpza.now.sh/)
- fixes:
  - [https://github.com/code-kotis/barcode-scanner/issues/46](https://github.com/code-kotis/barcode-scanner/issues/46)
  - [https://github.com/code-kotis/barcode-scanner/issues/36](https://github.com/code-kotis/barcode-scanner/issues/36)
  - [https://github.com/code-kotis/barcode-scanner/issues/30](https://github.com/code-kotis/barcode-scanner/issues/30)

### CODE REVIEW

**Comment by gokulkrishh** [comment]
@patrickpei Hi, Thanks for the PR. Much appreciated. There is a bug in safari mobile browser which prevented me to add mediaStream API for IOS. Bug is "When I add the app to home screen from safari in mobile and open it from homescreen, camera will not work." I will try to debug and fix this issue after that will merge the PR 👍

**Comment by patrickpei** [comment]
Could that be tracked in a separate issue? Opening it up to iOS is a big win especially with the limited & sort of hidden state of PWAs.

**Comment by gokulkrishh** [comment]
@patrickpei Yep I agree. But lets not keep too many issues as its related to https://github.com/code-kotis/barcode-scanner/issues/46 issue. I will follow up with bug status and keep you guys posted on this.

**Comment by jeanpablojp** [comment]
@patrickpei Where can i download the full code from the temporary demo?
I`ve got the last commit but its not working on IOS devices, but your temporary link works perfect.

Thanks in advance.

**Comment by patrickpei** [comment]
Temporary fork: https://github.com/patrickpei/barcode-scanner

**Comment by gokulkrishh** [comment]
@patrickpei I debugged the code after added to homescreen in IOS. Unfortunately safari add to homescreen is done via safari webview which doesn't have the mediaScreen API. We need to watch out the API release to safari webview then add this implementation you have done. Just FYI

**Comment by patrickpei** [comment]
Could you explain why you want to wait for that API change to merge this? This PR strictly increases the number of users this is available to and the overall functionality.

**Comment by gokulkrishh** [comment]
@patrickpei Sure. In pwa's mostly people add the app to homescreen and use it and some doesn't. In android everything works fine both app in browser and from the homescreen. In iOS, as of now we have capture a picture and make it work in both n browser and from the homescreen. 

Today I debugged the app in iOS after adding to homescreen. Found out the below

**IOS only**:

- MediaStream API is working in the browser. 
- After adding the app to homescreen and its webview from safari for homescreen apps, which doesn't have `MediaStream API`. We have to wait till apple dev's add's the same support to webview as well. Else user's wont be able to use the app after adding it to homescreen.

Hope this clear's your doubt and question.

Some more ref - https://stackoverflow.com/questions/45055329/does-webkit-in-ios-11-beta-support-webrtc?answertab=active#tab-top

**Comment by gokulkrishh** [comment]
@patrickpei Also I have one more idea. In order to merge this and make it work for IOS, we can keep both select from picture and scanning. If scanning doesn't work, user can use `select from picture` or use native camera to capture picture and use it. For this I need to change some implementation. I will work on this and see how this work.

**Comment by gokulkrishh** [comment]
@patrickpei I have opened a https://github.com/code-kotis/barcode-scanner/pull/52 to **add support iOS scanning** and **added a** **upload a picture/capture a picture** icon to scan the QR Code. 

Since I am iOS 12 public beta, capture the picture to scan is not working for me. I need someone to test 
it out and let me know if we can go ahead with above PR.

Demo: [https://qr123.surge.sh](https://qr123.surge.sh)

**Comment by chriswhardy** [comment]
Hi @gokulkrishh and @patrickpei 

Thanks for working on this and I've tried the demo's are they are excellent. Im currently building a web app where I use a mobile device to take a picture of a QR code and use that picture to obtain the information from the code itself. However the method displayed here allows all that to happen live which will be much easier for my users.

I've only just really started programming so my knowledge is very limited but I have already managed to create a demo of my web app to show some of the people I work with but I really want to take my idea further.

The problem I am having is that I can't seam to download and implement the code to look like the demo's your providing. I feel like, because of my limited knowledge, I'm missing something out. My hope was to take the idea you show here and just replace it with what I've done in my current demo web app. 

Could you possible give me some ideas on how to create the demo's to look like yours? I'm more than willing to share what I've managed to achieve so far if that would help. 

Thanks,

Chris

**Comment by gokulkrishh** [comment]
@chriswhardy Hey this repo is an open source. Feel free to fork and modify how ever you want it. Code written is very simple. I am sure you will be able to understand it. Hope this repo helps you!!!

**Comment by gokulkrishh** [comment]
Closing in favour of #52

**Pull request closed without merging**
